class Purchase < ApplicationRecord
  belongs_to :purchasable, polymorphic: true
  belongs_to :user
  belongs_to :payment_method
  #<Stripe::Charge:0x3ff8c20653d8 id=ch_1E54LqGR2qRuiC4IMxpgde0K> JSON: {
#   "id": "ch_1E54LqGR2qRuiC4IMxpgde0K",
#   "object": "charge",
#   "amount": 500,
#   "amount_refunded": 0,
#   "application": null,
#   "application_fee": null,
#   "application_fee_amount": null,
#   "balance_transaction": "txn_1E54LqGR2qRuiC4IqxshYyYN",
#   "captured": true,
#   "created": 1550466454,
#   "currency": "usd",
#   "customer": "cus_EYAhFWx9WVC10p",
#   "description": "Entry fee for a Mythic Championship Cleveland league on Thousand Leagues.",
#   "destination": null,
#   "dispute": null,
#   "failure_code": null,
#   "failure_message": null,
#   "fraud_details": {},
#   "invoice": null,
#   "livemode": false,
#   "metadata": {},
#   "on_behalf_of": null,
#   "order": null,
#   "outcome": {"network_status":"approved_by_network","reason":null,"risk_level":"normal","risk_score":1,"seller_message":"Payment complete.","type":"authorized"},
#   "paid": true,
#   "payment_intent": null,
#   "receipt_email": null,
#   "receipt_number": null,
#   "receipt_url": "https://pay.stripe.com/receipts/acct_194vhkGR2qRuiC4I/ch_1E54LqGR2qRuiC4IMxpgde0K/rcpt_EYAhnvzwbOStmSnDvwEEywaePyeAf8n",
#   "refunded": false,
#   "refunds": {"object":"list","data":[],"has_more":false,"total_count":0,"url":"/v1/charges/ch_1E54LqGR2qRuiC4IMxpgde0K/refunds"},
#   "review": null,
#   "shipping": null,
#   "source": {"id":"card_1E54LlGR2qRuiC4Ige10aUce","object":"card","address_city":"Edmonds","address_country":"United States","address_line1":"111 1st AVe","address_line1_check":"pass","address_line2":null,"address_state":"WA","address_zip":"98026","address_zip_check":"pass","brand":"Visa","country":"US","customer":"cus_EYAhFWx9WVC10p","cvc_check":null,"dynamic_last4":null,"exp_month":4,"exp_year":2019,"fingerprint":"3gtGa6JA8tNOWEf4","funding":"credit","last4":"4242","metadata":{},"name":"David","tokenization_method":null},
#   "source_transfer": null,
#   "statement_descriptor": null,
#   "status": "succeeded",
#   "transfer_data": null,
#   "transfer_group": null
# }
end
